
//://////////////////////////////////////////////////////////://
//:                                                          ://
//: DO NOT USE THIS FILE, TEST FUNCTIONS ARE STILL FUNCTIONS ://
//: AND BELONG IN [ GEP.FUNC.JS ]                            ://
//:                                                          ://
//: Logic Here:                                              ://
//: 1. Test functions are the same magnitude of importance.  ://
//:    Thus imperative that people can find test code.       ://
//:                                                          ://
//: 2: Having [GEP.TEST.JS] code at top level is a violation ://
//:    of "everything is either functions or data".          ://
//:                                                          ://
//://////////////////////////////////////////////////////////://